"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { getEquipment, getHomeMedia, getSpecials, type HomeMediaRecord, type SpecialRecord } from "@/lib/firebase/data";
import { readEquipment, type EquipmentItem } from "@/lib/equipment";

export default function Home() {
 const [equipment,setEquipment]=useState<EquipmentItem[]>([]); const [specials,setSpecials]=useState<SpecialRecord[]>([]); const [media,setMedia]=useState<HomeMediaRecord[]>([]);
 useEffect(()=>{let cancelled=false; void Promise.all([getEquipment(),getSpecials(true),getHomeMedia(true)]).then(([e,s,m])=>{if(!cancelled){setEquipment(e.length?e.filter(x=>x.active):readEquipment().filter(x=>x.active));setSpecials(s);setMedia(m)}}).catch(()=>{if(!cancelled)setEquipment(readEquipment().filter(x=>x.active))});return()=>{cancelled=true}},[]);
 return <main className="site">
  <div className="topbar"><div className="container topbarInner"><span>Avram Kids · kids entertainment & event equipment hire</span><strong>Gaborone, Botswana</strong></div></div>
  <nav className="nav"><div className="container navInner"><Link href="/" className="logo"><span className="logoMark" aria-hidden="true"/>Avram Kids</Link><div className="navLinks"><a href="#equipment">Equipment</a><a href="#how">How it works</a><a href="#specials">Specials</a></div><Link href="/book" className="button buttonPrimary">Book Online</Link></div></nav>
  <section className="hero"><div className="container heroGrid"><div><span className="eyebrow">Fun is ready to arrive</span><h1>Big fun for little moments.</h1><p>Vibrant Avram Kids inflatables and event equipment for birthdays, school days, family gatherings and celebrations in Gaborone.</p><div className="actions"><Link href="/book" className="button buttonPrimary">Start a booking</Link><a className="button buttonLight" href="#equipment">See equipment</a></div><p className="heroNote">Choose online · Share your event details once · Avram reviews your request</p></div><div className="heroArt" aria-label="Playful jumping castle illustration"><div className="blob"/><div className="blobTwo"/><div className="castle"><div className="tower left"/><div className="tower right"/><div className="castleMain"><div className="door"/></div></div></div></div></section>
  {media.length>0&&<section className="section sectionSoft"><div className="container"><div className="sectionHead"><span className="kicker">From Avram Kids</span><h2>What&apos;s ready for your event.</h2></div><div className="equipmentGrid">{media.map(x=><article className="equipmentCard" key={x.id}><div className="equipmentVisual">{x.type==="video"?<video src={x.publicUrl} controls playsInline style={{width:"100%",height:"100%",objectFit:"cover",borderRadius:"inherit"}}/>:<img src={x.publicUrl} alt={x.title} style={{width:"100%",height:"100%",objectFit:"cover",borderRadius:"inherit"}}/>}</div><h3>{x.title}</h3><p>{x.caption}</p></article>)}</div></div></section>}
  <section id="equipment" className="section"><div className="container"><div className="sectionHead"><span className="kicker">Equipment for hire</span><h2>Pick the fun that fits your event.</h2><p>Current equipment, sizes and prices, managed by Avram from Operations.</p></div><div className="equipmentGrid">{equipment.map(x=><article className="equipmentCard" key={x.id}><div className="equipmentTop"><span className="equipmentPill">FOR HIRE</span><strong>{x.price}</strong></div><div className="equipmentVisual">{x.imageUrl?<img src={x.imageUrl} alt={x.name} style={{width:"100%",height:"100%",objectFit:"cover",borderRadius:"inherit"}}/>:x.name.toLowerCase().includes("slide")?"💦":"🏰"}</div><h3>{x.name}</h3><p>{x.detail}</p><div className="equipmentMeta"><span>{x.size}</span><span>{x.price}</span></div><Link href={`/book?equipment=${encodeURIComponent(x.name)}`} className="button buttonLight">Request this</Link></article>)}</div></div></section>
  <section className="section sectionSoft"><div className="container"><div className="sectionHead"><span className="kicker">Simple booking</span><h2>Tell Avram once. The system keeps it organized.</h2></div><div className="steps"><article className="step"><span className="stepNo">01</span><h3>Choose equipment</h3><p>Browse real equipment, sizes and prices.</p></article><article className="step"><span className="stepNo">02</span><h3>Send one complete request</h3><p>Share date, location, event and contact details.</p></article><article className="step"><span className="stepNo">03</span><h3>Avram reviews</h3><p>The request stays organized in the Operations queue.</p></article><article className="step"><span className="stepNo">04</span><h3>Confirmation follows review</h3><p>Availability is checked before a booking is confirmed.</p></article></div></div></section>
  <section id="specials" className="section"><div className="container"><div className="sectionHead"><span className="kicker">Specials & packages</span><h2>{specials.length?"Current Avram offers":"Planning something bigger?"}</h2><p>{specials.length?"Real offers published by Avram Kids.":"Custom event packages can be requested through the booking form."}</p></div>{specials.length?<div className="cards">{specials.map(x=><article className="card" key={x.id}><h3>{x.title}</h3><p>{x.detail}</p>{x.offer&&<strong>{x.offer}</strong>}<div className="actions"><Link href="/book" className="button buttonLight">Request this</Link></div></article>)}</div>:<div className="actions"><Link href="/book" className="button buttonPrimary">Build my request</Link></div>}</div></section>
  <section className="section"><div className="container"><div className="sectionHead"><span className="kicker">The Avram standard</span><h2>Fun, with the practical bits covered.</h2></div><div className="trustGrid"><article className="trust"><h3>Clean & prepared</h3><p>Equipment is prepared before and after rentals, with safety rules communicated at setup.</p></article><article className="trust"><h3>Punctual & professional</h3><p>Local delivery, setup and takedown are handled around confirmed events.</p></article><article className="trust"><h3>One clear booking path</h3><p>Customers submit complete event details so Avram can review organized requests.</p></article></div></div></section>
  <section className="cta"><div className="container ctaInner"><div><span className="kicker">Ready when you are</span><h2>Let&apos;s plan the fun.</h2><p>Send your complete booking request online. Avram will review it and get back to you.</p></div><Link href="/book" className="button buttonDark">Book Avram Kids</Link></div></section>
  <footer className="footer"><div className="container footerGrid"><div><div className="logo"><span className="logoMark" aria-hidden="true"/>Avram Kids</div><p>Kids entertainment and event equipment hire in Gaborone, Botswana.</p></div><div><strong>Booking</strong><p><Link href="/book">Book online</Link></p></div><div><strong>Follow</strong><p><a href="https://www.facebook.com/avramkids/">Facebook</a><br/><a href="https://www.instagram.com/avramkids/">Instagram</a></p></div></div></footer>
 </main>;
}
