"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { readEquipment, saveEquipment, seedEquipment, type EquipmentItem } from "@/lib/equipment";

type BookingRequest = { id: string; createdAt: string; name: string; phone: string; email: string; date: string; startTime?: string; location: string; equipment: string; quantity: number; guests?: number; eventType: string; notes: string; status: "New" | "Contacted" | "Confirmed" | "Completed" | "Cancelled" };
type Special = { id: string; title: string; detail: string; active: boolean };
const BOOKINGS_KEY = "avram_booking_requests_v1";
const SPECIALS_KEY = "avram_specials_v1";
function loadBookings(): BookingRequest[] { try { return JSON.parse(localStorage.getItem(BOOKINGS_KEY) ?? "[]"); } catch { return []; } }
function loadSpecials(): Special[] { try { return JSON.parse(localStorage.getItem(SPECIALS_KEY) ?? "[]"); } catch { return []; } }
function isCompleteLead(item: BookingRequest) { return Boolean(item.name && item.phone && item.date && item.startTime && item.location && item.equipment && item.quantity > 0 && item.guests && item.eventType); }

export default function AdminPage() {
  const [tab, setTab] = useState<"requests" | "equipment" | "specials">("requests");
  const [bookings, setBookings] = useState<BookingRequest[]>([]); const [equipment, setEquipment] = useState<EquipmentItem[]>([]); const [specials, setSpecials] = useState<Special[]>([]);
  const [selected, setSelected] = useState<string | null>(null); const [filter, setFilter] = useState<"all" | "new" | "upcoming">("all");
  const [specialTitle, setSpecialTitle] = useState(""); const [specialDetail, setSpecialDetail] = useState(""); const [editingId, setEditingId] = useState<string | null>(null); const [draft, setDraft] = useState<EquipmentItem | null>(null); const [notice, setNotice] = useState("");
  useEffect(() => { setBookings(loadBookings()); setEquipment(readEquipment()); setSpecials(loadSpecials()); }, []);
  const counts = useMemo(() => ({ total: bookings.length, new: bookings.filter((item) => item.status === "New").length, qualified: bookings.filter(isCompleteLead).length, upcoming: bookings.filter((item) => item.date >= new Date().toISOString().slice(0, 10) && item.status !== "Cancelled").length }), [bookings]);
  const visibleBookings = useMemo(() => { const filtered = bookings.filter((item) => filter === "new" ? item.status === "New" : filter === "upcoming" ? item.date >= new Date().toISOString().slice(0, 10) && item.status !== "Cancelled" : true); return [...filtered].sort((a, b) => a.date.localeCompare(b.date) || b.createdAt.localeCompare(a.createdAt)); }, [bookings, filter]);
  function updateStatus(id: string, status: BookingRequest["status"]) { const next = bookings.map((item) => item.id === id ? { ...item, status } : item); setBookings(next); localStorage.setItem(BOOKINGS_KEY, JSON.stringify(next)); setNotice(`Booking marked ${status.toLowerCase()}.`); }
  function saveEquipmentItem() { if (!draft?.name.trim() || !draft.size.trim() || !draft.price.trim()) return; const next = equipment.some((item) => item.id === draft.id) ? equipment.map((item) => item.id === draft.id ? draft : item) : [...equipment, draft]; setEquipment(next); saveEquipment(next); setEditingId(null); setDraft(null); setNotice("Equipment saved. Customers can now see the updated listing."); }
  function startEdit(item: EquipmentItem) { setEditingId(item.id); setDraft({ ...item }); }
  function startAdd() { setEditingId("new"); setDraft({ id: crypto.randomUUID(), name: "", detail: "", size: "", price: "P0", active: true }); }
  function deleteEquipment(id: string) { const item = equipment.find((entry) => entry.id === id); if (!item || !window.confirm(`Remove “${item.name}” from the equipment list?`)) return; const next = equipment.filter((entry) => entry.id !== id); setEquipment(next); saveEquipment(next); setNotice("Equipment removed."); }
  function toggleEquipment(id: string) { const next = equipment.map((item) => item.id === id ? { ...item, active: !item.active } : item); setEquipment(next); saveEquipment(next); setNotice(next.find((item) => item.id === id)?.active ? "Equipment is now visible to customers." : "Equipment is now hidden from customers."); }
  function resetCatalogue() { if (!window.confirm("Restore the original Avram equipment list? Your catalogue changes will be removed.")) return; setEquipment(seedEquipment); saveEquipment(seedEquipment); setNotice("Original equipment list restored."); }
  function addSpecial(event: React.FormEvent) { event.preventDefault(); if (!specialTitle.trim()) return; const next = [...specials, { id: crypto.randomUUID(), title: specialTitle.trim(), detail: specialDetail.trim(), active: true }]; setSpecials(next); localStorage.setItem(SPECIALS_KEY, JSON.stringify(next)); setSpecialTitle(""); setSpecialDetail(""); setNotice("Special saved."); }
  function toggleSpecial(id: string) { const next = specials.map((item) => item.id === id ? { ...item, active: !item.active } : item); setSpecials(next); localStorage.setItem(SPECIALS_KEY, JSON.stringify(next)); }
  function deleteSpecial(id: string) { const next = specials.filter((item) => item.id !== id); setSpecials(next); localStorage.setItem(SPECIALS_KEY, JSON.stringify(next)); }
  function clearRequests() { if (!window.confirm("Clear all booking requests from this browser?")) return; localStorage.removeItem(BOOKINGS_KEY); setBookings([]); setSelected(null); setNotice("Booking requests cleared."); }
  const current = bookings.find((item) => item.id === selected) ?? null;

  return <main className="adminPage"><div className="adminShell">
    <header className="adminHeader"><div><span className="kicker">Avram Kids · Operations</span><h1>Operations dashboard</h1><p>Keep every booking request and equipment listing organized in one simple place.</p></div><div className="adminHeaderActions"><Link href="/" className="button buttonLight">View public site</Link><button className="button buttonLight" onClick={clearRequests}>Clear requests</button></div></header>
    <section className="adminStats"><article><span>Total requests</span><strong>{counts.total}</strong></article><article><span>New</span><strong>{counts.new}</strong></article><article><span>Ready to review</span><strong>{counts.qualified}</strong></article><article><span>Upcoming</span><strong>{counts.upcoming}</strong></article></section>
    <nav className="adminTabs" aria-label="Operations sections"><button className={tab === "requests" ? "active" : ""} onClick={() => setTab("requests")}>Booking requests</button><button className={tab === "equipment" ? "active" : ""} onClick={() => setTab("equipment")}>Equipment</button><button className={tab === "specials" ? "active" : ""} onClick={() => setTab("specials")}>Specials</button></nav>
    {notice && <div className="adminToast" role="status">{notice}</div>}
    {tab === "requests" && <section className="adminContent twoColumn"><div className="adminPanel"><div className="panelHeading"><div><span className="kicker">Owner queue</span><h2>Booking requests</h2></div><span>{bookings.length} total</span></div><div className="adminFilters"><button className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>All</button><button className={filter === "new" ? "active" : ""} onClick={() => setFilter("new")}>Needs review ({counts.new})</button><button className={filter === "upcoming" ? "active" : ""} onClick={() => setFilter("upcoming")}>Upcoming ({counts.upcoming})</button></div>{visibleBookings.length === 0 ? <div className="emptyState"><div>📋</div><h3>No requests in this view</h3><p>Customers can submit complete booking requests through the public booking page.</p><Link href="/book" className="button buttonPrimary">Open booking page</Link></div> : <div className="requestList">{visibleBookings.map((item) => <button key={item.id} className={`requestRow ${selected === item.id ? "selected" : ""}`} onClick={() => setSelected(item.id)}><div><strong>{item.name}</strong><span>{item.equipment} × {item.quantity}</span></div><div><strong>{item.date}</strong><span>{isCompleteLead(item) ? "Ready to review" : item.status}</span></div></button>)}</div>}</div><div className="adminPanel detailPanel">{current ? <><div className="panelHeading"><div><span className="kicker">Request details</span><h2>{current.name}</h2></div><select value={current.status} onChange={(event) => updateStatus(current.id, event.target.value as BookingRequest["status"])}><option>New</option><option>Contacted</option><option>Confirmed</option><option>Completed</option><option>Cancelled</option></select></div><dl className="detailList"><div><dt>Event</dt><dd>{current.date} · {current.startTime || "Time not specified"} · {current.eventType || "Not specified"}</dd></div><div><dt>Guests</dt><dd>{current.guests || "Not specified"}</dd></div><div><dt>Equipment</dt><dd>{current.equipment} × {current.quantity}</dd></div><div><dt>Location</dt><dd>{current.location}</dd></div><div><dt>Phone</dt><dd><a href={`tel:${current.phone}`}>{current.phone}</a></dd></div><div><dt>Email</dt><dd>{current.email || "Not provided"}</dd></div><div><dt>Notes</dt><dd>{current.notes || "No additional notes."}</dd></div></dl><div className="actions"><a className="button buttonPrimary" href={`https://wa.me/${current.phone.replace(/\D/g, "")}`}>Contact on WhatsApp</a><a className="button buttonLight" href={`tel:${current.phone}`}>Call</a></div></> : <div className="emptyState"><div>👈</div><h3>Select a request</h3><p>Choose a request to see the complete event brief, then contact the customer only when you are ready.</p></div>}</div></section>}
    {tab === "equipment" && <section className="adminContent"><div className="adminPanel"><div className="panelHeading"><div><span className="kicker">What customers can book</span><h2>Equipment</h2><p>Add, edit, hide or remove items from your equipment list.</p></div><div className="actions"><button className="button buttonPrimary" onClick={startAdd}>+ Add equipment</button><button className="button buttonLight" onClick={resetCatalogue}>Restore original list</button></div></div><div className="equipmentAdminGrid">{equipment.map((item) => <article key={item.id}><div><strong>{item.name}</strong><span>{item.detail} · {item.size}</span></div><b>{item.price}</b><span>{item.active ? "Visible" : "Hidden"}</span><div className="actions"><button className="button buttonLight" onClick={() => toggleEquipment(item.id)}>{item.active ? "Hide" : "Show"}</button><button className="button buttonLight" onClick={() => startEdit(item)}>Edit</button><button className="button buttonLight" onClick={() => deleteEquipment(item.id)}>Delete</button></div></article>)}</div></div>{draft && <div className="adminPanel"><div className="panelHeading"><div><span className="kicker">{editingId === "new" ? "New listing" : "Edit listing"}</span><h2>{editingId === "new" ? "Add equipment" : "Edit equipment"}</h2><p>Use simple, customer-friendly wording for the name, size and price.</p></div><button className="button buttonLight" onClick={() => { setDraft(null); setEditingId(null); }}>Cancel</button></div><form className="adminForm" onSubmit={(event) => { event.preventDefault(); saveEquipmentItem(); }}><label>Name<input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} placeholder="e.g. Blue Castle" required /></label><label>Description<input value={draft.detail} onChange={(event) => setDraft({ ...draft, detail: event.target.value })} placeholder="Short description" required /></label><label>Size<input value={draft.size} onChange={(event) => setDraft({ ...draft, size: event.target.value })} placeholder="e.g. 3 × 6 m" required /></label><label>Price<input value={draft.price} onChange={(event) => setDraft({ ...draft, price: event.target.value })} placeholder="e.g. P600" required /></label><label><input type="checkbox" checked={draft.active} onChange={(event) => setDraft({ ...draft, active: event.target.checked })} /> Show this equipment on the website</label><button className="button buttonPrimary" type="submit">Save equipment</button></form></div>}</section>}
    {tab === "specials" && <section className="adminContent twoColumn"><div className="adminPanel"><div className="panelHeading"><div><span className="kicker">Content</span><h2>Specials</h2></div><span>{specials.filter((item) => item.active).length} active</span></div>{specials.length === 0 ? <div className="emptyState"><div>✨</div><h3>No specials yet</h3><p>Add a special when there is a real offer you want customers to see.</p></div> : <div className="specialList">{specials.map((item) => <article key={item.id}><div><strong>{item.title}</strong><p>{item.detail || "No detail added."}</p></div><div className="actions"><button className="button buttonLight" onClick={() => toggleSpecial(item.id)}>{item.active ? "Active" : "Hidden"}</button><button className="button buttonLight" onClick={() => deleteSpecial(item.id)}>Delete</button></div></article>)}</div>}</div><div className="adminPanel"><div className="panelHeading"><div><span className="kicker">Create</span><h2>Add a special</h2></div></div><form onSubmit={addSpecial} className="adminForm"><label>Title<input value={specialTitle} onChange={(event) => setSpecialTitle(event.target.value)} placeholder="e.g. Weekend package" required /></label><label>Detail<textarea value={specialDetail} onChange={(event) => setSpecialDetail(event.target.value)} placeholder="Describe the real offer." /></label><button className="button buttonPrimary" type="submit">Save special</button></form></div></section>}
  </div></main>;
}
