"use client";

import { useEffect, useState } from "react";
import { deleteObject, getDownloadURL, ref, uploadBytes } from "firebase/storage";
import { auth, storage } from "@/lib/firebase/client";
import { getHomeMedia, getSpecials, saveHomeMediaRecord, saveSpecialRecord, deleteHomeMediaRecord, deleteSpecialRecord, type HomeMediaRecord, type SpecialRecord } from "@/lib/firebase/data";
import AdminGate from "@/app/admin/admin-gate";

export default function ContentAdminPage() {
  const [specials, setSpecials] = useState<SpecialRecord[]>([]);
  const [media, setMedia] = useState<HomeMediaRecord[]>([]);
  const [special, setSpecial] = useState<SpecialRecord | null>(null);
  const [mediaDraft, setMediaDraft] = useState<HomeMediaRecord | null>(null);
  const [file, setFile] = useState<File | null>(null);
  const [notice, setNotice] = useState("");
  async function load() { try { setSpecials(await getSpecials()); setMedia(await getHomeMedia()); } catch { setNotice("Content could not be loaded from Firebase."); } }
  useEffect(() => { void load(); }, []);

  async function saveSpecial() { if (!special?.title.trim()) return; try { await saveSpecialRecord(special); setSpecials((x) => x.some((i) => i.id === special.id) ? x.map((i) => i.id === special.id ? special : i) : [...x, special]); setSpecial(null); setNotice("Special saved."); } catch { setNotice("Special could not be saved."); } }
  async function removeSpecial(id: string) { if (!window.confirm("Delete this special?")) return; try { await deleteSpecialRecord(id); setSpecials((x) => x.filter((i) => i.id !== id)); } catch { setNotice("Special could not be deleted."); } }

  async function saveMedia() {
    if (!mediaDraft?.title.trim() || (!mediaDraft.publicUrl && !file)) return;
    let next = mediaDraft;
    if (file) { if (!auth.currentUser) { setNotice("Please sign in again."); return; } if (!file.type.startsWith("image/") && !file.type.startsWith("video/")) { setNotice("Choose an image or video."); return; } try { const safe = file.name.toLowerCase().replace(/[^a-z0-9.-]+/g, "-"); const path = `homepage-media/${next.id}/${Date.now()}-${safe}`; const result = await uploadBytes(ref(storage, path), file, { contentType: file.type }); next = { ...next, type: file.type.startsWith("video/") ? "video" : "image", storagePath: path, publicUrl: await getDownloadURL(result.ref), updatedAt: new Date().toISOString() }; } catch { setNotice("Media upload failed."); return; } }
    try { await saveHomeMediaRecord(next); setMedia((x) => x.some((i) => i.id === next.id) ? x.map((i) => i.id === next.id ? next : i) : [...x, next].sort((a, b) => a.order - b.order)); setMediaDraft(null); setFile(null); setNotice("Homepage media saved."); } catch { setNotice("Media record could not be saved."); }
  }
  async function removeMedia(item: HomeMediaRecord) { if (!window.confirm("Remove this homepage media?")) return; try { if (item.storagePath) { try { await deleteObject(ref(storage, item.storagePath)); } catch {} } await deleteHomeMediaRecord(item.id); setMedia((x) => x.filter((i) => i.id !== item.id)); } catch { setNotice("Media could not be removed."); } }

  return <AdminGate><main className="adminPage"><div className="adminShell"><header className="adminHeader"><div><span className="kicker">Avram Kids · Content</span><h1>Public site content</h1><p>Everything here is live managed content. Firebase is the source of truth.</p></div></header>{notice && <div className="adminToast" role="status">{notice}</div>}
    <section className="adminContent twoColumn"><div className="adminPanel"><div className="panelHeading"><div><span className="kicker">Promotions</span><h2>Specials</h2></div><button className="button buttonPrimary" onClick={() => setSpecial({ id: crypto.randomUUID(), title: "", detail: "", active: true })}>+ Add special</button></div>{specials.map((item) => <article className="specialList" key={item.id}><div><strong>{item.title}</strong><p>{item.detail}</p>{item.offer && <b>{item.offer}</b>}</div><div className="actions"><button className="button buttonLight" onClick={() => void saveSpecialRecord({ ...item, active: !item.active }).then(() => setSpecials((x) => x.map((i) => i.id === item.id ? { ...i, active: !i.active } : i)))}>{item.active ? "Hide" : "Publish"}</button><button className="button buttonLight" onClick={() => setSpecial({ ...item })}>Edit</button><button className="button buttonLight" onClick={() => void removeSpecial(item.id)}>Delete</button></div></article>)}{special && <form className="adminForm" onSubmit={(e) => { e.preventDefault(); void saveSpecial(); }}><label>Title<input value={special.title} onChange={(e) => setSpecial({ ...special, title: e.target.value })} required /></label><label>Description<textarea value={special.detail} onChange={(e) => setSpecial({ ...special, detail: e.target.value })} required /></label><label>Offer wording<input value={special.offer ?? ""} onChange={(e) => setSpecial({ ...special, offer: e.target.value })} /></label><label><input type="checkbox" checked={special.active} onChange={(e) => setSpecial({ ...special, active: e.target.checked })} /> Published</label><div className="actions"><button className="button buttonPrimary">Save</button><button type="button" className="button buttonLight" onClick={() => setSpecial(null)}>Cancel</button></div></form>}</div>
    <div className="adminPanel"><div className="panelHeading"><div><span className="kicker">Homepage</span><h2>Images & videos</h2></div><button className="button buttonPrimary" onClick={() => setMediaDraft({ id: crypto.randomUUID(), type: "image", storagePath: "", publicUrl: "", title: "", caption: "", active: true, order: media.length, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() })}>+ Add media</button></div>{media.map((item) => <article className="specialList" key={item.id}><div>{item.publicUrl && (item.type === "video" ? <video src={item.publicUrl} controls style={{ width: 120, height: 80, objectFit: "cover", borderRadius: 10 }} /> : <img src={item.publicUrl} alt="" style={{ width: 120, height: 80, objectFit: "cover", borderRadius: 10 }} />)}<strong>{item.title}</strong><p>{item.caption}</p></div><div className="actions"><button className="button buttonLight" onClick={() => void saveHomeMediaRecord({ ...item, active: !item.active, updatedAt: new Date().toISOString() }).then(() => setMedia((x) => x.map((i) => i.id === item.id ? { ...i, active: !i.active } : i)))}>{item.active ? "Hide" : "Publish"}</button><button className="button buttonLight" onClick={() => setMediaDraft({ ...item })}>Edit</button><button className="button buttonLight" onClick={() => void removeMedia(item)}>Delete</button></div></article>)}{mediaDraft && <form className="adminForm" onSubmit={(e) => { e.preventDefault(); void saveMedia(); }}><label>Title<input value={mediaDraft.title} onChange={(e) => setMediaDraft({ ...mediaDraft, title: e.target.value })} required /></label><label>Caption<input value={mediaDraft.caption} onChange={(e) => setMediaDraft({ ...mediaDraft, caption: e.target.value })} /></label><label>File<input type="file" accept="image/*,video/*" onChange={(e) => setFile(e.target.files?.[0] ?? null)} required={!mediaDraft.publicUrl} /></label><label>Order<input type="number" min="0" value={mediaDraft.order} onChange={(e) => setMediaDraft({ ...mediaDraft, order: Number(e.target.value) })} /></label><label><input type="checkbox" checked={mediaDraft.active} onChange={(e) => setMediaDraft({ ...mediaDraft, active: e.target.checked })} /> Published</label><div className="actions"><button className="button buttonPrimary">Save media</button><button type="button" className="button buttonLight" onClick={() => setMediaDraft(null)}>Cancel</button></div></form>}</div></section>
  </div></main></AdminGate>;
}
